Repository SaiSatwik2226/approx_circuits, pull requests merged in 2021-10, with the labels that each got.

#6 Create fullAdder.cpp
  fullAdder.cpp
Labels: enhancement, good first issue, hacktoberfest, **hacktoberfest-accepted**, hacktoberfest-accepted

#8 Create halfAdder.h
  halfAdder.h
Labels: enhancement, good first issue, hacktoberfest, **hacktoberfest-accepted**, hacktoberfest-accepted

#10 Create halfAdder.cpp
  halfAdder.cpp
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest-accepted

#11 Correct spelling errors in README.md
  README.md
Labels: good first issue, hacktoberfest, **hacktoberfest-accepted**, hacktoberfest-accepted

#13 Create ahma.cpp
  ahma.cpp
Labels: enhancement, good first issue, hacktoberfest, **hacktoberfest-accepted**, hacktoberfest-accepted

#17 Create exact_4_2.cpp
  exact_4_2.cpp
Labels: enhancement, hacktoberfest, **hacktoberfest-accepted**, hacktoberfest-accepted

#19 created ahma.h
  ahma.h
Labels: enhancement, good first issue, hacktoberfest, **hacktoberfest-accepted**, hacktoberfest-accepted

#23 updated with relevant details
  README.md
Labels: documentation, good first issue, hacktoberfest, **hacktoberfest-accepted**, hacktoberfest-accepted

#25 deleted redundant folder
  #include<bits/haldAdder.cpp
Labels: enhancement, good first issue, hacktoberfest, **hacktoberfest-accepted**, hacktoberfest-accepted

#26 Update ahma.cpp
  ahma.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#28 Update exact_4_2.cpp
  exact_4_2.cpp
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#31 Update fullAdder.cpp
  fullAdder.cpp
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#32 Update halfAdder.cpp
  halfAdder.cpp
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#35 updated to bool in exact 5-3
  exact_4_2.h
Labels: enhancement, hacktoberfest, **hacktoberfest-accepted**, hacktoberfest-accepted

#36 Update fullAdder.h
  fullAdder.h
Labels: hacktoberfest, **hacktoberfest-accepted**, hacktoberfest-accepted

#37 Update fullAdder.h
  fullAdder.h
Labels: hacktoberfest, **hacktoberfest-accepted**, hacktoberfest-accepted

#38 Update halfAdder.h
  halfAdder.h
Labels: hacktoberfest, **hacktoberfest-accepted**, hacktoberfest-accepted

#40 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: hacktoberfest

#41 Create CONTRIBUTING.md
  CONTRIBUTING.md
Labels: hacktoberfest, hacktoberfest-accepted
